# Generated by Django 4.2.7 on 2023-12-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='categoryName',
            field=models.CharField(max_length=100),
        ),
    ]
